# Generated by Django 6.0.1 on 2026-02-04 20:32

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('name', models.CharField(db_index=True, help_text='Nombre de la liga (ej: NFL, NBA, Liga MX)', max_length=100, unique=True, verbose_name='nombre')),
                ('sport', models.CharField(db_index=True, help_text='Tipo de deporte (ej: Fútbol Americano, Basketball)', max_length=50, verbose_name='deporte')),
                ('country', models.CharField(blank=True, default='', help_text='País de origen de la liga', max_length=50, verbose_name='país')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si la liga está activa y se consideran sus eventos', verbose_name='activa')),
                ('base_priority', models.PositiveSmallIntegerField(default=5, help_text='Prioridad base de la liga (1=máxima, 10=mínima)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='prioridad base')),
            ],
            options={
                'verbose_name': 'liga',
                'verbose_name_plural': 'ligas',
                'ordering': ['base_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('code', models.CharField(db_index=True, help_text='Código único de la categoría (ej: AM, INS, MID, NS)', max_length=10, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=50, verbose_name='nombre')),
                ('min_traders', models.PositiveSmallIntegerField(default=0, help_text='Número mínimo de traders requeridos para esta categoría', validators=[django.core.validators.MaxValueValidator(50)], verbose_name='mínimo de traders')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción detallada del turno', verbose_name='descripción')),
                ('typical_start_time', models.TimeField(blank=True, help_text='Hora aproximada de inicio de turnos en esta categoría', null=True, verbose_name='hora típica de inicio')),
                ('typical_end_time', models.TimeField(blank=True, help_text='Hora aproximada de fin de turnos en esta categoría', null=True, verbose_name='hora típica de fin')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Orden para mostrar en interfaces de usuario', verbose_name='orden de visualización')),
            ],
            options={
                'verbose_name': 'categoría de turno',
                'verbose_name_plural': 'categorías de turno',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('weekend_scheduling', models.BooleanField(default=True, help_text='Si el algoritmo puede asignar turnos en sábado y domingo', verbose_name='permitir turnos en fines de semana')),
                ('max_consecutive_days', models.PositiveSmallIntegerField(default=6, help_text='Máximo de días consecutivos de trabajo permitidos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)], verbose_name='máximo días consecutivos')),
                ('min_rest_hours', models.PositiveSmallIntegerField(default=8, help_text='Horas mínimas de descanso entre turnos', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(24)], verbose_name='horas mínimas de descanso')),
                ('auto_approval', models.BooleanField(default=False, help_text='Si los swap requests se aprueban automáticamente tras aceptación del compañero', verbose_name='auto-aprobación de solicitudes')),
                ('notification_email_enabled', models.BooleanField(default=True, help_text='Habilitar envío de notificaciones por correo electrónico', verbose_name='notificaciones por email')),
                ('notification_whatsapp_enabled', models.BooleanField(default=False, help_text='Habilitar envío de notificaciones por WhatsApp', verbose_name='notificaciones por WhatsApp')),
                ('default_algorithm_version', models.CharField(default='v1.0', help_text='Versión del algoritmo de generación a usar por defecto', max_length=20, verbose_name='versión del algoritmo')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('employee_id', models.CharField(db_index=True, help_text='Código interno único del empleado (ej: EMP-001)', max_length=20, unique=True, verbose_name='código de empleado')),
                ('phone', models.CharField(blank=True, default='', help_text='Número de teléfono para notificaciones WhatsApp', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Use formato internacional.', regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono')),
                ('role', models.CharField(choices=[('MONITOR_TRADER', 'Monitor Trader'), ('INPLAY_TRADER', 'In-Play Trader'), ('MANAGER', 'Manager/Supervisor'), ('ADMIN', 'Administrador')], db_index=True, default='MONITOR_TRADER', help_text='Rol del empleado en la organización', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el empleado está activo. Usar para soft delete.', verbose_name='activo')),
                ('hire_date', models.DateField(blank=True, help_text='Fecha en que el empleado fue contratado', null=True, verbose_name='fecha de contratación')),
                ('user', models.OneToOneField(help_text='Usuario Django asociado a este empleado', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('preferred_shift_category', models.ForeignKey(blank=True, help_text='Preferencia de turno del empleado (considerado como soft constraint)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_employees', to='api.shiftcategory', verbose_name='categoría de turno preferida')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftCycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('name', models.CharField(help_text='Nombre descriptivo de la configuración (ej: "Ciclo Monitor")', max_length=50, unique=True, verbose_name='nombre')),
                ('trader_role', models.CharField(choices=[('MONITOR_TRADER', 'Monitor Trader'), ('INPLAY_TRADER', 'In-Play Trader'), ('MANAGER', 'Manager/Supervisor'), ('ADMIN', 'Administrador')], db_index=True, help_text='Rol de trader al que aplica esta configuración', max_length=20, verbose_name='rol de trader')),
                ('shift_order', models.JSONField(help_text='Lista ordenada de códigos de turno ["MON6", "MON12", "OFF"]', validators=[api.models.validate_shift_order], verbose_name='orden de ciclo')),
                ('is_default', models.BooleanField(default=False, help_text='Si es la configuración por defecto para el rol', verbose_name='es configuración por defecto')),
                ('include_off', models.BooleanField(default=True, help_text='Si el ciclo incluye el código OFF (día libre)', verbose_name='incluir OFF en ciclo')),
                ('include_vac', models.BooleanField(default=False, help_text='Si el ciclo incluye el código VAC (vacaciones)', verbose_name='incluir VAC en ciclo')),
            ],
            options={
                'verbose_name': 'configuración de ciclo',
                'verbose_name_plural': 'configuraciones de ciclo',
                'ordering': ['trader_role', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('trader_role',), name='unique_default_per_role')],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('code', models.CharField(db_index=True, help_text='Código único del tipo de turno (ej: MON6, IP9, OFF)', max_length=10, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text='Nombre completo del tipo de turno', max_length=100, verbose_name='nombre')),
                ('start_time', models.TimeField(blank=True, help_text='Hora de inicio del turno (null para OFF/VAC)', null=True, verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, help_text='Hora de fin del turno (null para OFF/VAC)', null=True, verbose_name='hora de fin')),
                ('is_working_shift', models.BooleanField(db_index=True, default=True, help_text='False para turnos no operativos como OFF y VAC', verbose_name='es turno laboral')),
                ('color_code', models.CharField(default='#6B7280', help_text='Color hexadecimal para mostrar en UI (ej: #FF5733)', max_length=7, validators=[api.models.validate_hex_color], verbose_name='código de color')),
                ('applicable_to_monitor', models.BooleanField(default=True, help_text='Si este turno puede asignarse a Monitor Traders', verbose_name='aplicable a Monitor Trader')),
                ('applicable_to_inplay', models.BooleanField(default=True, help_text='Si este turno puede asignarse a In-Play Traders', verbose_name='aplicable a In-Play Trader')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si este tipo de turno está disponible para asignación', verbose_name='activo')),
                ('category', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece (null para OFF/VAC)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_types', to='api.shiftcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'tipo de turno',
                'verbose_name_plural': 'tipos de turno',
                'ordering': ['category__display_order', 'start_time', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('date', models.DateField(db_index=True, help_text='Fecha de la asignación', verbose_name='fecha')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Fecha/hora de inicio calculada', null=True, verbose_name='inicio')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Fecha/hora de fin calculada', null=True, verbose_name='fin')),
                ('title', models.CharField(blank=True, default='', help_text='Título personalizado opcional', max_length=100, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', help_text='Notas adicionales de la asignación', verbose_name='descripción')),
                ('edit_source', models.CharField(choices=[('ALGORITHM', 'Generación automática'), ('GRID_EDIT', 'Edición en grid'), ('BULK_IMPORT', 'Importación masiva'), ('SWAP', 'Intercambio de turno'), ('MANUAL', 'Creación manual')], db_index=True, default='MANUAL', help_text='Cómo fue creada/modificada esta asignación', max_length=20, verbose_name='origen')),
                ('edit_history', models.JSONField(blank=True, default=list, help_text='Historial de ediciones [{timestamp, user_id, from_code, to_code}]', verbose_name='historial de cambios')),
                ('last_edited_at', models.DateTimeField(blank=True, help_text='Timestamp de la última edición en grid', null=True, verbose_name='fecha de última edición')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('employee', models.ForeignKey(help_text='Empleado asignado a este turno', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee', verbose_name='empleado')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última edición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_edits', to=settings.AUTH_USER_MODEL, verbose_name='última edición por')),
                ('shift_type', models.ForeignKey(help_text='Tipo de turno asignado', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='api.shifttype', verbose_name='tipo de turno')),
            ],
            options={
                'verbose_name': 'asignación de turno',
                'verbose_name_plural': 'asignaciones de turno',
                'ordering': ['date', 'employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('name', models.CharField(help_text='Nombre del evento (ej: "Super Bowl LVIII")', max_length=200, verbose_name='nombre')),
                ('date_start', models.DateTimeField(db_index=True, help_text='Fecha y hora de inicio del evento', verbose_name='fecha/hora de inicio')),
                ('date_end', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del evento (opcional)', null=True, verbose_name='fecha/hora de fin')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=5, help_text='Prioridad del evento (1=máxima, 10=mínima)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='prioridad')),
                ('description', models.TextField(blank=True, default='', help_text='Notas adicionales sobre el evento', verbose_name='descripción')),
                ('external_id', models.CharField(blank=True, help_text='ID del sistema externo para sincronización', max_length=100, null=True, unique=True, verbose_name='ID externo')),
                ('league', models.ForeignKey(help_text='Liga a la que pertenece el evento', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.league', verbose_name='liga')),
            ],
            options={
                'verbose_name': 'evento deportivo',
                'verbose_name_plural': 'eventos deportivos',
                'ordering': ['-date_start', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de respuesta del compañero'), ('ACCEPTED_BY_PEER', 'Aceptado por compañero, pendiente de admin'), ('REJECTED_BY_PEER', 'Rechazado por compañero'), ('APPROVED', 'Aprobado por administrador'), ('REJECTED_BY_ADMIN', 'Rechazado por administrador'), ('CANCELLED', 'Cancelado por solicitante')], db_index=True, default='PENDING', help_text='Estado actual de la solicitud', max_length=20, verbose_name='estado')),
                ('reason', models.TextField(blank=True, default='', help_text='Razón de la solicitud de intercambio', verbose_name='motivo')),
                ('peer_response_at', models.DateTimeField(blank=True, help_text='Cuándo respondió el compañero', null=True, verbose_name='fecha de respuesta del compañero')),
                ('peer_response_note', models.TextField(blank=True, default='', help_text='Comentario del compañero al responder', verbose_name='nota del compañero')),
                ('admin_response_at', models.DateTimeField(blank=True, help_text='Cuándo respondió el administrador', null=True, verbose_name='fecha de respuesta del admin')),
                ('admin_response_note', models.TextField(blank=True, default='', help_text='Comentario del admin al aprobar/rechazar', verbose_name='nota del administrador')),
                ('admin_responder', models.ForeignKey(blank=True, help_text='Administrador que procesó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_processed', to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
                ('requester', models.ForeignKey(help_text='Empleado que inicia la solicitud de intercambio', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='api.employee', verbose_name='solicitante')),
                ('requester_schedule', models.ForeignKey(help_text='Turno que el solicitante ofrece intercambiar', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_offered', to='api.schedule', verbose_name='turno ofrecido')),
                ('target_employee', models.ForeignKey(help_text='Empleado al que se solicita el intercambio', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='api.employee', verbose_name='destinatario')),
                ('target_schedule', models.ForeignKey(help_text='Turno que el solicitante desea obtener', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requested', to='api.schedule', verbose_name='turno solicitado')),
            ],
            options={
                'verbose_name': 'solicitud de intercambio',
                'verbose_name_plural': 'solicitudes de intercambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('name', models.CharField(db_index=True, help_text='Nombre único del equipo', max_length=100, unique=True, verbose_name='nombre del equipo')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción opcional del equipo y sus responsabilidades', verbose_name='descripción')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el equipo está activo en el sistema', verbose_name='activo')),
                ('manager', models.ForeignKey(blank=True, help_text='Empleado que lidera este equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='api.employee', verbose_name='manager')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Equipo al que pertenece el empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.team', verbose_name='equipo'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único público para uso en API', unique=True, verbose_name='identificador único')),
                ('start_date', models.DateField(db_index=True, help_text='Primer día de vacaciones', verbose_name='fecha de inicio')),
                ('end_date', models.DateField(db_index=True, help_text='Último día de vacaciones', verbose_name='fecha de fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', help_text='Estado de la solicitud', max_length=20, verbose_name='estado')),
                ('reason', models.TextField(blank=True, default='', help_text='Razón o notas de la solicitud', verbose_name='motivo')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Cuándo fue procesada la solicitud', null=True, verbose_name='fecha de aprobación')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Explicación si fue rechazada', verbose_name='motivo de rechazo')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrador que aprobó/rechazó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacations_approved', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('employee', models.ForeignKey(help_text='Empleado que solicita las vacaciones', on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='api.employee', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'vacaciones',
                'verbose_name_plural': 'vacaciones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación', verbose_name='fecha de actualización')),
                ('month', models.PositiveSmallIntegerField(help_text='Mes para el que se generó el horario (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mes')),
                ('year', models.PositiveSmallIntegerField(help_text='Año para el que se generó el horario', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('status', models.CharField(choices=[('SUCCESS', 'Completado exitosamente'), ('PARTIAL', 'Completado con advertencias'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado por usuario')], db_index=True, default='SUCCESS', help_text='Resultado de la generación', max_length=20, verbose_name='estado')),
                ('total_assignments', models.PositiveIntegerField(default=0, help_text='Número de asignaciones creadas', verbose_name='total de asignaciones')),
                ('events_considered', models.PositiveIntegerField(default=0, help_text='Número de eventos deportivos considerados', verbose_name='eventos considerados')),
                ('traders_scheduled', models.PositiveIntegerField(default=0, help_text='Número de traders incluidos en el horario', verbose_name='traders programados')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Lista de advertencias durante la generación', verbose_name='advertencias')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Lista de errores durante la generación', verbose_name='errores')),
                ('algorithm_decisions', models.JSONField(blank=True, default=list, help_text='Log de decisiones tomadas por el algoritmo', verbose_name='decisiones del algoritmo')),
                ('execution_time_seconds', models.FloatField(default=0.0, help_text='Tiempo total de ejecución en segundos', verbose_name='tiempo de ejecución')),
                ('algorithm_version', models.CharField(default='v1.0', help_text='Versión del algoritmo utilizada', max_length=20, verbose_name='versión del algoritmo')),
                ('parameters_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot de los parámetros usados (min_traders, etc.)', verbose_name='parámetros')),
                ('generated_by', models.ForeignKey(help_text='Usuario que ejecutó la generación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_generations', to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
            ],
            options={
                'verbose_name': 'log de generación',
                'verbose_name_plural': 'logs de generación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['year', 'month'], name='api_schedul_year_29b0d7_idx'), models.Index(fields=['status', 'created_at'], name='api_schedul_status_0ded29_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shifttype',
            index=models.Index(fields=['is_working_shift', 'is_active'], name='api_shiftty_is_work_692da6_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'shift_type'], name='api_schedul_date_ee0e59_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['employee', 'date'], name='api_schedul_employe_11ace6_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'edit_source'], name='api_schedul_date_26251e_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date'),
        ),
        migrations.AddIndex(
            model_name='sportevent',
            index=models.Index(fields=['date_start', 'priority'], name='api_sportev_date_st_c771dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sportevent',
            index=models.Index(fields=['league', 'date_start'], name='api_sportev_league__7a3958_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['status', 'created_at'], name='api_swapreq_status_545256_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['requester', 'status'], name='api_swapreq_request_8f0296_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['target_employee', 'status'], name='api_swapreq_target__3f93fb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role', 'is_active'], name='api_employe_role_968344_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['team', 'is_active'], name='api_employe_team_id_c667b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vacation',
            index=models.Index(fields=['employee', 'status'], name='api_vacatio_employe_fcec20_idx'),
        ),
        migrations.AddIndex(
            model_name='vacation',
            index=models.Index(fields=['start_date', 'end_date'], name='api_vacatio_start_d_738b34_idx'),
        ),
    ]
