# Generated by Django 6.0.1 on 2026-01-26 17:31

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi Grupo', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Número de factura para display (ej: INV-2026-00001)', max_length=50, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('paid', 'Pagada'), ('void', 'Anulada'), ('uncollectible', 'Incobrable')], default='draft', max_length=20)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA u otros impuestos', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuentos aplicados (cupones, etc.)', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto efectivamente pagado', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pendiente de pago', max_digits=10)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite de pago', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, default='', max_length=200)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago'), ('conekta', 'Conekta'), ('manual', 'Manual/Transferencia')], max_length=30)),
                ('external_id', models.CharField(help_text='ID del método en la pasarela (ej: pm_xxxx en Stripe)', max_length=255)),
                ('method_type', models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria'), ('oxxo', 'OXXO'), ('spei', 'SPEI')], max_length=30)),
                ('last_four', models.CharField(blank=True, default='', help_text='Últimos 4 dígitos (solo para display)', max_length=4)),
                ('card_brand', models.CharField(blank=True, default='', max_length=50)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_default', models.BooleanField(default=False, help_text='Si es el método de pago predeterminado')),
                ('is_valid', models.BooleanField(default=True, help_text='Si el método sigue siendo válido (puede expirar o ser rechazado)')),
                ('billing_address', models.JSONField(blank=True, default=dict, help_text='Dirección de facturación: {street, city, state, postal_code, country}')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID del plan en la pasarela de pago (ej: price_xxxxx en Stripe)', max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('lifetime', 'Vitalicio')], default='monthly', max_length=20)),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Días de prueba gratuita (0 = sin trial)')),
                ('is_active', models.BooleanField(default=True, help_text='Si está disponible para nuevas suscripciones')),
                ('is_public', models.BooleanField(default=True, help_text='Si aparece en la UI pública (False para planes legacy)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del plan (límites, características, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Blitz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('matched', 'Emparejado')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('location', models.JSONField(default=dict)),
                ('activity_type', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_sessions', to='api.group')),
            ],
            options={
                'verbose_name_plural': 'Blitz Sessions',
                'db_table': 'blitz_sessions',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('chatting', 'En Chat'), ('met', 'Se Encontraron'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('meeting_location', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blitz_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first', to='api.blitz')),
                ('blitz_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second', to='api.blitz')),
                ('chat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='api.chat')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('event_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blitz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='api.blitz')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='api.match')),
            ],
            options={
                'db_table': 'location_logs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID del pago en pasarela (ej: pi_xxxx, ch_xxxx)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolso Parcial')], default='pending', max_length=30)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión cobrada por la pasarela', max_digits=10)),
                ('failure_reason', models.CharField(blank=True, choices=[('insufficient_funds', 'Fondos Insuficientes'), ('card_declined', 'Tarjeta Rechazada'), ('expired_card', 'Tarjeta Expirada'), ('incorrect_cvc', 'CVC Incorrecto'), ('processing_error', 'Error de Procesamiento'), ('fraud_detected', 'Fraude Detectado'), ('authentication_required', '3DS Requerido'), ('limit_exceeded', 'Límite Excedido'), ('other', 'Otro')], max_length=50, null=True)),
                ('failure_message', models.TextField(blank=True, default='', help_text='Mensaje de error de la pasarela')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.paymentmethod')),
            ],
            options={
                'db_table': 'billing_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('subscription', 'Suscripción'), ('proration', 'Prorrateo'), ('one_time', 'Cargo Único'), ('discount', 'Descuento'), ('tax', 'Impuesto')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=10)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan')),
            ],
            options={
                'db_table': 'billing_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto Fijo')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 20.00) o monto fijo', max_digits=10)),
                ('currency', models.CharField(default='MXN', help_text='Solo aplica si es fixed_amount', max_length=3)),
                ('duration', models.CharField(choices=[('once', 'Una Vez'), ('repeating', 'Repetitivo'), ('forever', 'Para Siempre')], max_length=20)),
                ('duration_in_months', models.PositiveIntegerField(blank=True, help_text="Solo si duration='repeating'", null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Usos máximos totales (null = ilimitado)', null=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='coupons', to='api.plan')),
            ],
            options={
                'db_table': 'billing_coupons',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text="Clave única para usar en código (ej: 'max_groups', 'unlimited_blitz')", max_length=100)),
                ('feature_name', models.CharField(help_text="Nombre para mostrar al usuario (ej: 'Grupos máximos')", max_length=200)),
                ('value', models.CharField(help_text="Valor: 'true'/'false' para flags, número para límites, 'unlimited' para sin límite", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción para mostrar en página de precios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.plan')),
            ],
            options={
                'db_table': 'billing_plan_features',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID de suscripción en pasarela (ej: sub_xxxx en Stripe)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('trialing', 'En Prueba'), ('active', 'Activa'), ('past_due', 'Pago Vencido'), ('unpaid', 'Impaga'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('paused', 'Pausada')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(help_text='Fecha en que termina el periodo actual y se debe renovar/cobrar')),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='Si está en trial, fecha en que termina y se cobra', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Si True, se cancela al final del periodo actual (no inmediatamente)')),
                ('cancel_reason', models.CharField(blank=True, choices=[('user_request', 'Solicitud del Usuario'), ('payment_failed', 'Pago Fallido'), ('fraud', 'Fraude Detectado'), ('admin', 'Cancelado por Admin'), ('upgraded', 'Upgrade a Otro Plan'), ('downgraded', 'Downgrade a Otro Plan'), ('other', 'Otro')], max_length=30, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, help_text='Si está en past_due, fecha límite para pagar antes de suspensión', null=True)),
                ('billing_cycle_count', models.PositiveIntegerField(default=0, help_text='Número de ciclos de facturación completados')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.paymentmethod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.plan')),
            ],
            options={
                'db_table': 'billing_subscriptions',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.subscription'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Cuando expira el descuento', null=True)),
                ('remaining_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.coupon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.subscription')),
            ],
            options={
                'db_table': 'billing_discounts',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='api.subscription')),
            ],
            options={
                'db_table': 'billing_usage_records',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('profile_photo', models.URLField(blank=True, default='', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['firebase_uid'], name='users_firebas_361636_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx')],
            },
            bases=(api.models.UserBillingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.user'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.user')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('blitz_match', 'Nuevo Match'), ('blitz_like', 'Grupo te dio Like'), ('new_message', 'Nuevo Mensaje'), ('friend_request', 'Solicitud de Amistad'), ('group_invite', 'Invitación a Grupo'), ('blitz_expiring', 'Blitz por Expirar'), ('system', 'Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_sent', models.BooleanField(default=False)),
                ('fcm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('location', 'Ubicación'), ('system', 'Sistema')], default='text', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.user')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.user'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('admin', 'Administrador')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='api.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='api.GroupMembership', to='api.user'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('blocked', 'Bloqueado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to='api.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='api.user')),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to='api.user'),
        ),
        migrations.AddField(
            model_name='blitz',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_blitz_sessions', to='api.user'),
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('event_id', models.CharField(db_index=True, help_text='ID del evento en la pasarela (para idempotencia)', max_length=255)),
                ('event_type', models.CharField(help_text='Tipo de evento (ej: invoice.payment_succeeded)', max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('ignored', 'Ignorado')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_webhook_logs',
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_web_provide_fb1148_idx'), models.Index(fields=['event_type', 'status'], name='billing_web_event_t_766cad_idx'), models.Index(fields=['created_at'], name='billing_web_created_6992c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlitzInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('skip', 'Skip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_blitz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_made', to='api.blitz')),
                ('to_blitz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to='api.blitz')),
            ],
            options={
                'db_table': 'blitz_interactions',
                'indexes': [models.Index(fields=['from_blitz', 'interaction_type'], name='blitz_inter_from_bl_bdd126_idx'), models.Index(fields=['to_blitz', 'interaction_type'], name='blitz_inter_to_blit_5b693b_idx')],
                'unique_together': {('from_blitz', 'to_blitz')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'created_at'], name='matches_status_abf324_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['latitude', 'longitude'], name='location_lo_latitud_e96395_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['created_at'], name='location_lo_created_fea38e_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['event_type', 'created_at'], name='location_lo_event_t_ffab8e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='billing_pay_invoice_bdbc34_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='billing_pay_externa_d8c1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='billing_pay_status_05bcfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together={('plan', 'feature_key')},
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['subscription', 'feature_key', 'period_start'], name='billing_usa_subscri_55ba2a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='billing_sub_user_id_e5f6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_7f7f12_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['external_id'], name='billing_sub_externa_55d505_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='billing_pay_user_id_e547e1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider', 'external_id'], name='billing_pay_provide_433829_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='messages_chat_id_ec31ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messages_sender__bf8b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='billing_inv_user_id_3f3549_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_1d4853_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['external_id'], name='billing_inv_externa_871bb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user_from', 'status'], name='friendships_user_fr_b9a5af_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user_to', 'status'], name='friendships_user_to_2a791e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user_from', 'user_to')},
        ),
        migrations.AddIndex(
            model_name='blitz',
            index=models.Index(fields=['status', 'expires_at'], name='blitz_sessi_status_52c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='blitz',
            index=models.Index(fields=['status', 'created_at'], name='blitz_sessi_status_ef4edb_idx'),
        ),
    ]
