# Generated by Django 6.0.1 on 2026-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exclude_from_grid',
            field=models.BooleanField(default=False, help_text='Si es True, el empleado no aparece en la grilla de horarios', verbose_name='excluir de grilla'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('MONITOR_TRADER', 'Monitor Trader'), ('INPLAY_TRADER', 'In-Play Trader'), ('PREMATCH_TRADER', 'Pre-Match Trader'), ('MANAGER', 'Manager/Supervisor'), ('ADMIN', 'Administrador')], db_index=True, default='MONITOR_TRADER', help_text='Rol del empleado en la organización', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='shiftcycleconfig',
            name='trader_role',
            field=models.CharField(choices=[('MONITOR_TRADER', 'Monitor Trader'), ('INPLAY_TRADER', 'In-Play Trader'), ('PREMATCH_TRADER', 'Pre-Match Trader'), ('MANAGER', 'Manager/Supervisor'), ('ADMIN', 'Administrador')], db_index=True, help_text='Rol de trader al que aplica esta configuración', max_length=20, verbose_name='rol de trader'),
        ),
    ]
