# Generated by Django 6.0.1 on 2026-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_prematch_role_and_exclude_from_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='away_team',
            field=models.CharField(blank=True, default='', help_text='Nombre del equipo visitante', max_length=150, verbose_name='equipo visitante'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='home_team',
            field=models.CharField(blank=True, default='', help_text='Nombre del equipo local', max_length=150, verbose_name='equipo local'),
        ),
    ]
